# We don't use github projects, disabling
name: Add PRs to project Reviewing PRs

on:
  pull_request:
    types:
      - opened

jobs:
  add-PR-to-project:
    if : false
    name: Add PRs to project Reviewing PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.1.0
        with:
          project-url: https://github.com/orgs/calcom/projects/11
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
